repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        stages: [commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.9.1
    hooks:
      - id: isort
        args: [--profile, black, --filter-files]
        stages: [commit]
